# Generated by Django 5.0.7 on 2024-07-30 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_description'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_first_n_a7e990_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
