# Generated by Django 5.0.7 on 2024-07-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_customer_store_custo_first_n_a7e990_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='membership',
            field=models.CharField(choices=[('B', 'Bronze'), ('S', 'Sliver'), ('G', 'Gold')], default='B', max_length=1, null=True),
        ),
    ]
