# Generated by Django 5.0.7 on 2024-07-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='membership',
        ),
        migrations.AddField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('B', 'Bronze'), ('S', 'Sliver'), ('G', 'Gold')], default='B', max_length=1),
        ),
    ]
